apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  url: aHR0cHM6Ly9naXRodWIuY29tL2Rldm9wcy1pbnRoZS1lYXN0L3BldC1kZXRlY3Rvci1hcHAuZ2l0
  username: ZGV2b3BzLWludGhlLWVhc3Q=
  password: Z2hwXzl5TzJtZUhjaWMwY3dKM3U0dDM5VmVGRDA4SEZRWDB6eENaMw==
